name: Generate a mongrel

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Pillow
    - name: Unpack assets
      run: |
        unzip -qq -P ${{ secrets.ASSETS_PASSWORD }} assets.zip
    - name: Get the configuration
      run: printf '${{ secrets.CONFIGURATION }}' >> configuration.json
    - name: Generate a mongrel json
      run: python ./generate_mongrels.py --count 5 --seed 3
    - name: Generate a mongrel image
      run: python ./generate_images.py --scale=2
    - name: Archive the generated mongrel
      uses: actions/upload-artifact@v4
      with:
        name: generated-mongrel
        path: images/
        if-no-files-found: error
    - name: Upload image
      id: upload_image
      uses: McCzarny/upload-image@v1.3.0
      if: github.event_name == 'pull_request'
      with:
        path: |
          images/0.png
          images/1.png
          images/2.png
          images/3.png
          images/4.png
        uploadMethod: imgbb
        apiKey: '${{ secrets.IMGBB_API_KEY }}'
    - name: 'Comment PR'
      uses: actions/github-script@v7.0.1
      if: github.event_name == 'pull_request'
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Images: \n![0](${{fromJson(steps.upload_image.outputs.urls)[0]}})![1](${{fromJson(steps.upload_image.outputs.urls)[1]}})![2](${{fromJson(steps.upload_image.outputs.urls)[2]}})![3](${{fromJson(steps.upload_image.outputs.urls)[3]}})![4](${{fromJson(steps.upload_image.outputs.urls)[4]}})'
            });
